#!/usr/bin/env bash
# factory/new-team.sh — Interactive: create or update a team via the governance repo
# Usage: bash factory/new-team.sh

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../lib/common.sh"

load_config
check_prereqs

: "${PLATFORM_ORG:?Run setup-all.sh first or set PLATFORM_ORG in $CONFIG_FILE}"
: "${GOVERNANCE_REPO:?Run setup-all.sh first or set GOVERNANCE_REPO in $CONFIG_FILE}"
: "${GITHUB_ORG:=${PLATFORM_ORG}}"

clear
header "New Team Request"
info "This will guide you through creating a new team in $GITHUB_ORG."
info "Answers generate a YAML definition and a PR to $PLATFORM_ORG/$GOVERNANCE_REPO."
echo ""

# ── Team basics ────────────────────────────────────────────────────────────────
step "1. Team Identity"

required_input "Team display name (e.g. Payments Backend)" TEAM_NAME

# Auto-generate slug from name
AUTO_SLUG=$(echo "$TEAM_NAME" | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr -cd 'a-z0-9-')
optional_input "Team slug (URL-safe, auto-generated from name)" TEAM_SLUG "$AUTO_SLUG"
# Validate slug
if [[ ! "$TEAM_SLUG" =~ ^[a-z0-9][a-z0-9-]*$ ]]; then
  error "Slug must be lowercase alphanumeric with hyphens only."
  exit 1
fi

if team_exists "$GITHUB_ORG" "$TEAM_SLUG"; then
  warn "Team '$TEAM_SLUG' already exists in $GITHUB_ORG."
  confirm "Update the existing team's members and settings?" || { info "Cancelled."; exit 0; }
  UPDATE_MODE=true
else
  UPDATE_MODE=false
fi

required_input "Team description (what does this team own?)" TEAM_DESCRIPTION

# ── Visibility ─────────────────────────────────────────────────────────────────
echo ""
step "2. Team Visibility"
echo ""
echo -e "  ${DIM}1${NC}. ${BOLD}closed${NC}  — visible to all org members (recommended)"
echo -e "  ${DIM}2${NC}. ${BOLD}secret${NC}  — hidden from non-members (use for security-sensitive groups)"
read -rp "$(echo -e "  ${CYAN}Select [1]: ${NC}")" VIS_CHOICE
PRIVACY=$( [[ "${VIS_CHOICE:-1}" == "2" ]] && echo "secret" || echo "closed" )
info "  Privacy: $PRIVACY"

# ── Parent team ────────────────────────────────────────────────────────────────
echo ""
step "3. Parent Team (optional)"
info "Teams can be nested — e.g. payments-backend under engineering."
info "The parent team must already exist."
optional_input "Parent team slug (blank = top-level team)" PARENT_TEAM ""

if [[ -n "$PARENT_TEAM" ]]; then
  if ! team_exists "$GITHUB_ORG" "$PARENT_TEAM"; then
    warn "Parent team '$PARENT_TEAM' not found. It must be created first."
    confirm "Continue anyway?" || exit 1
  fi
fi

# ── Members ────────────────────────────────────────────────────────────────────
echo ""
step "4. Team Members"
echo ""
info "Maintainers can add/remove members. At least one maintainer is required."
info "Press Enter with a blank username to finish each list."

MAINTAINERS_YAML="maintainers:"
MAINTAINER_COUNT=0
echo ""
echo -e "  ${BOLD}Maintainers:${NC}"
while true; do
  read -rp "$(echo -e "    Username (blank to finish): ")" username
  [[ -z "$username" ]] && break
  MAINTAINERS_YAML+=$'\n'"  - \"$username\""
  MAINTAINER_COUNT=$((MAINTAINER_COUNT + 1))
  success "  Added maintainer: $username"
done

if [[ $MAINTAINER_COUNT -eq 0 ]]; then
  error "At least one maintainer is required."
  exit 1
fi

MEMBERS_YAML="members:"
echo ""
echo -e "  ${BOLD}Members:${NC}"
while true; do
  read -rp "$(echo -e "    Username (blank to finish): ")" username
  [[ -z "$username" ]] && break
  MEMBERS_YAML+=$'\n'"  - \"$username\""
  success "  Added member: $username"
done

# ── Request metadata ───────────────────────────────────────────────────────────
echo ""
step "5. Request Metadata"
CURRENT_USER=$(gh api /user --jq '.login' 2>/dev/null || echo "")
optional_input "Your GitHub username" REQUESTED_BY "${CURRENT_USER}"
required_input "Business justification (why does this team need to exist?)" BIZ_JUSTIFICATION

# ── Generate YAML ──────────────────────────────────────────────────────────────
echo ""
step "Generating YAML definition"

YAML_CONTENT="# Team definition — auto-generated by new-team.sh
# Requested by: $REQUESTED_BY on $(date -u +%Y-%m-%d)

name: \"$TEAM_NAME\"
slug: \"$TEAM_SLUG\"
description: \"$TEAM_DESCRIPTION\"
privacy: $PRIVACY
parent_team: \"${PARENT_TEAM:-}\"

$MAINTAINERS_YAML

$MEMBERS_YAML

requested_by: \"$REQUESTED_BY\"
business_justification: \"$BIZ_JUSTIFICATION\""

echo ""
echo -e "${DIM}──────────── Generated YAML ────────────${NC}"
echo "$YAML_CONTENT"
echo -e "${DIM}────────────────────────────────────────${NC}"
echo ""

confirm "Submit this as a PR to $PLATFORM_ORG/$GOVERNANCE_REPO?" || {
  info "Cancelled. No changes made."
  exit 0
}

# ── Create PR ──────────────────────────────────────────────────────────────────
step "Creating Pull Request"

TEMP_DIR=$(mktemp -d)
trap "rm -rf $TEMP_DIR" EXIT

info "Cloning governance repository..."
gh repo clone "$PLATFORM_ORG/$GOVERNANCE_REPO" "$TEMP_DIR/governance" -- --depth 1 --quiet

cd "$TEMP_DIR/governance"

BRANCH_NAME="team-request/${TEAM_SLUG}-$(date +%Y%m%d-%H%M%S)"
git checkout -b "$BRANCH_NAME" &>/dev/null

mkdir -p teams
echo "$YAML_CONTENT" > "teams/${TEAM_SLUG}.yml"

git config user.email "${REQUESTED_BY}@github.com"
git config user.name "$REQUESTED_BY"
git add "teams/${TEAM_SLUG}.yml"
git commit -m "$( [[ "$UPDATE_MODE" == "true" ]] && echo "fix" || echo "feat"): $( [[ "$UPDATE_MODE" == "true" ]] && echo "update" || echo "create") team ${TEAM_SLUG}

Requested by: $REQUESTED_BY
Justification: $BIZ_JUSTIFICATION" --quiet

git push origin "$BRANCH_NAME" --quiet

ACTION=$( [[ "$UPDATE_MODE" == "true" ]] && echo "Update" || echo "New" )
PR_URL=$(gh pr create \
  --title "$ACTION team: $TEAM_NAME ($TEAM_SLUG)" \
  --body "## Team Request: $TEAM_NAME

**Slug:** \`$TEAM_SLUG\`
**Description:** $TEAM_DESCRIPTION
**Privacy:** $PRIVACY
**Parent team:** ${PARENT_TEAM:-none}
**Requested by:** @$REQUESTED_BY

### Members
$(echo "$MAINTAINERS_YAML" | grep -v '^maintainers:' | sed 's/  - /- (maintainer) /')
$(echo "$MEMBERS_YAML" | grep -v '^members:' | sed 's/  - /- (member) /')

### Justification
$BIZ_JUSTIFICATION

> Platform admin: verify members have valid SSO-linked accounts, then approve and merge." \
  --repo "$PLATFORM_ORG/$GOVERNANCE_REPO" \
  --base main \
  --head "$BRANCH_NAME")

cd - &>/dev/null

echo ""
success "Pull Request created: $PR_URL"
echo ""
info "On approval and merge, the team will be created/updated automatically."
